### ISSUE TITLE
uninitialized constant RBing 

### ISSUE THREAD

**Issue by rubydog** [mikedemers/rbing#3]
steps to reproduce error

`gem install rbing`

`require 'rubygems'
   require 'rbing' 
bing = RBing.new("APPID")`

doing so give me following error

```./rbing.rb:3: uninitialized constant RBing (NameError)
    from /Users/bhushan/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in`gem_original_require'
    from /Users/bhushan/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from rbing.rb:2

```
```

**Comment by rubydog** [comment]
I tried to do same with `irb`

`require 'rubygems'
require 'rbing`

gives me

```from ./rbing.rb:3
    from /Users/bhushan/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in`gem_original_require'
    from /Users/bhushan/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from (irb):2

```
```
